domain_path: C:\l12\software\kr260_platform\export\kr260_platform\sw\freertos_psu_cortexa53_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\freertos_hello_world
template: freertos_hello_world
